### ISSUE TITLE
Playing from Spotify

### ISSUE THREAD

**Issue by JTMachine** [sonos-web/sonos-web#15]
Can't play music from 'Spotify' Tab/Music Library. 

I can't seem to play any of the songs/playlists that appear in the spotify tab. It simply doesn't do anything when I press 'Play' or 'Add to end of que', 'Play next' or 'Replace que'. I'm using a spotify premium account, so not sure what else I am missing. 

Additionally, Music Library just gives me '404:Item not found', what does the music library pull it's info from and is that location something I can change in a config? (I can see a 'Shares' tab that is presumably for a NAS of some sort? 

Lastly, is there any scope for adding a child lock feature to the app at all? It'd be really useful to be able to lock down control to the devices for small periods of time. 

Thanks for the awesome app!

**Comment by Villarrealized** [comment]
I'm not sure why Spotify wouldn't work if you have a Premium account and have properly authenticated it within Sonos Web. What OS are you running Sonos Web on? And is it the same machine you are accessing the web browser from?

Music Library just pulls from whatever you have already setup on your Sonos system which would include any NAS or music available on your network. So if you can access music from your network via the official Sonos controller app, then you should be able to access it via Sonos Web.

I don't think I am planning on adding that sort of feature for the time being. Unfortunately I don't have a ton of time right now to develop extra features, but perhaps in the future.

You're welcome! Thanks for checking out the project.

**Comment by JTMachine** [comment]
Hiya - Running Sonos-web on MacOS Mojave, (which also has the authenticated spotify app) and logged into spotify using Sonos-webs login page. I have tried accessing spotify playlists both on the local machine and on other machines through the sonos-web app but with no luck.

Ah, thank you for clarifying that for me, I'll just set up a NAS and get music downloaded to there. 

Thanks again!

**Comment by Villarrealized** [comment]
Hmm. Well I am also running MacOS Mojave and can access Spotify just fine after logging in. If you are trying to access Spotify from a different machine than the one you installed it on, you will need to refer to this comment to get it working properly.

https://github.com/Villarrealized/sonos-web/issues/5#issuecomment-466656027

Can you confirm that Spotify works when playing directly from the official Sonos App?

**Comment by JTMachine** [comment]
Heya, 

I'll check the bits in that comment out and double check. 

Spotify works both when used from the mobile app (Sonos) and also from the Spotify Desktop app. 

Thanks,

EDIT: Once a playlist in spotify has been started (through the spotify desktop app) I am then able to play/pause/skip tracks, but not play specific ones (as they aren't appearing in the que).

**Comment by JTMachine** [comment]
Hiya, 

I made the changes as detailed in the other ticket, to no avail. I also then nuked the install and tried everything from scratch but am back to the same point. (where I can manage a playlist thats been started through the spotify app). 

Any ideas? 

Thanks!

**Comment by the-Joe** [comment]
Same here. Tried it on both Ubuntu & Mac OS X.

**Comment by the-Joe** [comment]
I spent some time troubleshooting my problem here and was able to get it running.
My setup:

Sonos Amp
Ubuntu 18.04.2 LTS
Chrome Version 74.0.3729.169

Like was said earlier in the thread, I was having the same issue with sonos-web. Was able to authenticate Spotify through the application and see my playlists but they wouldn't play. Also got 404 errors when navigating to "Music Library" & "My Sonos". Tried running from different browsers and also installing sonos-web on my MacBook Pro. Didn't resolve the issue.

It's worth mentioning at this point that this is the first Sonos device in my house and I'd never linked Spotify before and have no music in my sonos library currently.

This eventually brought me to the Sonos app on my iPhone. Since authorizing Spotify via sonos-web the Sonos app on my phone now had access to Spotify as well. I found a song and played via the Sonos app and suddenly sonos-web started working. It now seems to be working as expected and I'm able to select and play songs & playlists from Spotify on sonos-web. I'm sure if I added local music to the Music Library they'd eliminate the 404 errors as well. Will follow up when I get around to that.

* One caveat:
I have around 45 playlists on Spotify. sonos-web seems to have a pagination issue where it lists 45 playlists for me, but is simply repeating the same 12 or so over and over again.

**Comment by JTMachine** [comment]
@Villarrealized 

Just top update you again, this is what I'm getting: 

`xhr.js:178 PUT http://MYIP:5050/api/groups/RINCON_7828CAA47D6E01400:3241282575/playNow 500 (Internal Server Error)
(anonymous) @ xhr.js:178
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:59
Promise.then (async)
s.request @ Axios.js:51
s.<computed> @ Axios.js:71
(anonymous) @ bind.js:9
playNow @ groups.js:24
playNow @ Spotify Songs.8f3afb0e.js:1
click @ Spotify Album.15cc76c1.js:1
ne @ vue.runtime.esm.js:1847
n @ vue.runtime.esm.js:2169
ne @ vue.runtime.esm.js:1847
t.$emit @ vue.runtime.esm.js:3841
click @ routable.js:36
ne @ vue.runtime.esm.js:1847
n @ vue.runtime.esm.js:2169
Ji.o._wrapper @ vue.runtime.esm.js:6855
createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at t.exports (createError.js:16)
    at t.exports (settle.js:18)
    at XMLHttpRequest.p.<computed> (xhr.js:77)`

I am no where near adept enough to understand this, thanks for helping! :D

**Comment by Villarrealized** [comment]
Going to close this for now as I don't have Spotify premium anymore and I'm not able to debug this issue without it. Feel free to open again if someone else would like to tackle it.
