### ISSUE TITLE
can't install v0.9.6

### ISSUE THREAD

**Issue by peissl-at** [sonos-web/sonos-web#31]
Hello,

I've been using sonos-web for a long time and I really like it. Unfortunately i can't install the new version. I did the following ...

```
root@sonos-web2:~# npm install -g sonos-web-cli
/usr/bin/sonos-web -> /usr/lib/node_modules/sonos-web-cli/index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/sonos-web-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ sonos-web-cli@1.3.1
removed 2 packages and updated 2 packages in 25.286s
root@sonos-web2:~# sonos-web install           
Installing Sonos Web
✔ downloading installation files
✖ installing front-end dependencies
error installation failed...check /root/.sonos-web/install.log for more details
root@sonos-web2:~# cat /root/.sonos-web/install.log     
root@sonos-web2:~# cd /root/.sonos-web   
root@sonos-web2:~/.sonos-web# ls -al                         
total 64
drwxr-xr-x 4 root root  4096 Jan  5 07:08 .
drwx------ 6 root root  4096 Jan  5 07:08 ..
-rw-r--r-- 1 root root   232 Jan  4 15:41 .gitignore
-rw-r--r-- 1 root root 35149 Jan  4 15:41 LICENSE
-rw-r--r-- 1 root root  6083 Jan  4 15:41 README.md
drwxr-xr-x 6 root root  4096 Jan  5 07:08 client
-rw-r--r-- 1 root root     0 Jan  5 07:08 install.log
drwxr-xr-x 3 root root  4096 Jan  5 07:08 server
root@sonos-web2:~/.sonos-web# 
```

The log file is empty. I'm using Ubuntu 19.10 on a Intel(R) Celeron(R) CPU G1610. 
Is my system not supported? What could I do?

Sonnig Greetings!
Robert

**Comment by pwt** [comment]
I'm seeing the same symptoms, performing the installation on a Raspberry Pi. The install is in a container (running Raspbian Buster), but that shouldn't make a difference.

Install steps shown below:

```
root@f35a3af7c7d4:/# npm install -g sonos-web-cli
/usr/local/bin/sonos-web -> /usr/local/lib/node_modules/sonos-web-cli/index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/sonos-web-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ sonos-web-cli@1.3.1
added 419 packages from 210 contributors in 59.507s
root@f35a3af7c7d4:/# sonos-web install
Installing Sonos Web
✔ downloading installation files
✖ installing front-end dependencies
error installation failed...check /root/.sonos-web/install.log for more details
root@f35a3af7c7d4:/# ls -l /root/.sonos-web/install.log
-rw-r--r-- 1 root root 0 Jan  5 09:55 /root/.sonos-web/install.log
root@f35a3af7c7d4:/# node -v
v13.1.0
root@f35a3af7c7d4:/# 
```

**Comment by Villarrealized** [comment]
Hmm.

I need to see if I can fix that log output since it’s not helpful.

Let’s try this the manual way guys.

Below are the manual install steps that the cli runs automatically. Please let me know which error it fails on.

```bash
git clone https://github.com/Villarrealized/sonos-web.git
cd sonos-web/client
npm install
npm run build
cd ../server
npm install --only=production
```

It might be something about the version of node. I installed fine using sonos-web-cli on my raspberry-pi.
![Screen Shot 2020-01-05 at 6 41 24 AM](https://user-images.githubusercontent.com/5977736/71780974-93cc8a00-2f86-11ea-8cfb-f0130c48be19.png)
![Screen Shot 2020-01-05 at 6 42 28 AM](https://user-images.githubusercontent.com/5977736/71780975-95964d80-2f86-11ea-9360-3907b8e98ee8.png)

And on my Mac, no issues.

![Screen Shot 2020-01-05 at 6 43 27 AM](https://user-images.githubusercontent.com/5977736/71780988-b9f22a00-2f86-11ea-8ad3-51d8bec35349.png)

**Comment by pwt** [comment]
Performing the manual build steps above, before the normal build/install steps, actually fixes the problem for me with v0.9.8. The steps I used are:

```
# apt-get update && \
    apt-get -y install git python3 g++ build-essential

# git clone https://github.com/Villarrealized/sonos-web.git && \
    cd sonos-web/client && \
    npm install && \
    npm run build && \
    cd ../server && \
    npm install --only=production

# npm install -g sonos-web-cli
# sonos-web install
```

I have no expertise in Node, so I don't know if all of these steps are necessary.

**Comment by peissl-at** [comment]
Thank you very much, that helped me.

But I have one more...😉
If I reboot the system without first stoping sonos-web, then i have error 1. exactly as described here:
https://github.com/Villarrealized/sonos-web/issues/6#issuecomment-506263049
So I have to reinstall it to use it again.

Example:
After starting the system the website is not accessible. Therefore I want to restart sonos web.
```
root@sonos-web:~# sonos-web start
Sonos Web is already running
```
So I try to stop it.
```
root@sonos-web:~# sonos-web stop
✖ Stopping Sonos Web
error 1
```
Since that doesn't work either I have to do an update
```
root@sonos-web:~# sonos-web update
Stopping Sonos Web if it is running...
✖ Stopping Sonos Web
error 1
✔ Uninstalling Sonos Web
Installing Sonos Web
✔ downloading installation files
✔ installing front-end dependencies
✔ build front-end application
✔ install back-end dependencies
✔ cleaning up installation files
✔ Starting Sonos Web

success Open a web browser on this computer to http://localhost:5050 to start!
You can access Sonos Web network-wide by going to http://192.168.1.40:5050
root@sonos-web:~# 
```
The website is now available again.
It looks like a restart will destroy the installation?
That was also the case with version 0.9.4

**Comment by Villarrealized** [comment]
Thanks for the additional info @peissl-at. This issue likely has to do with how I'm using the npm package `forever` which allows sonos-web to run in the background without needing to have your terminal open the entire time. I'll try to see if there is a solution that I can implement.

Would you mind creating a new issue with the info in your last post?  Just helps keep things more clearly defined since it is a different issue than in your OP. Thanks!

**Comment by peissl-at** [comment]
Done!

Sunny Greetings!

**Comment by mattguide** [comment]
I ran into this today on sonos-web-cli 1.3.1.  
The `/root/.sonos-web/install.log` didn't have any errors, but going through each of the install steps and running `npm install build --loglevel verbose` for the front-end dependencies, I encountered this [thread id key 0x7777 error](https://stackoverflow.com/questions/67330252/thread-id-key-0x7777-function-find-thread-id-key-file-src-coroutine-cc).

The problem is caused by package `fibers` having a breaking change in **node 16.**  
The solution was to **downgrade to node 15** and it installed like a charm.

@Villarrealized - I am not sure where it would be specified, but the list of dependencies for sonos-web-cli should include `node < 16` at this point.

I was using the [node docker](https://hub.docker.com/_/node) container.  BTW - Thanks for this app--I can't wait to get it running! Still working on the solution to the error from #41 .
